name: Publish Docker Image

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker Image
        run: |
          docker login ghcr.io --username dhirudurgade7758 --password ${{ secrets.MY_PAT }}
          docker build . -t ghcr.io/dhirudurgade7758/chat-app-image
          docker push ghcr.io/dhirudurgade7758/chat-app-image